### PR TITLE
[Work in Progress] Executable and options

### PR DESCRIPTION
**Pull request by oalders**
@skaji this conflates adding an executable and also adding options.  I can break this up if that's better for you.

### CODE REVIEW

**Comment by skaji** [comment]
First of all, I want to note that:
one of the reasons why I created this checker is that INC directories may depend on working directories.
https://github.com/skaji/syntax-check-perl/blob/master/lib/Checker/Impl/Compile.pm#L61

**Comment by oalders** [comment]
Sure, that makes sense to me, but in a lot of cases I need some arbitrary paths in `@INC` in order for the script to compile, like 't/lib', 'dev/t/lib', 'dev/lib'.  Those won't get picked up by the logic in the checker.

**Comment by oalders** [comment]
I had a closer look at what's going on and I realized that I need to explicitly pass on @INC in order to make this work for me.  I've done so in the latest commit.  I'm happy to keep a fork going for the time being.  I was wondering what your motivation is for paring down @INC before running the command?

**Comment by oalders** [comment]
@skaji any suggestions on how to proceed with this? For my particular use case, including `lib` is not enough.  I need, for example to add `t/lib`, and 4 or 5 other directories relative to my working directory depending on the project.  These changes allow me to do that. 

Having said that, this PR as it stands will add some redundant dirs to `@INC`, it's not 100% correct, but I was wondering if you had a preferred way to move forward with this.  If I can't include these libs, then I can't get past a compile check.

**Comment by oalders** [comment]
I think allowing something like `ale_perl_syntax_check_options` to be passed to `syntax-check` via an `--options` switch would do the trick.  `syntax-check` could then include this in the compile command and that should take care of the issue and there would be no need to change the logic in `_inc()`. What do you think?

**Comment by skaji** [comment]
How about this?

* (a) Add `g:ale_perl_syntax_check_executable` option to vimrc as you implemented.
* (b) Add `inc` option to `config.pl`


As for (b), here is an example:
```perl
my $filename = $ENV{PERL_SYNTAX_CHECK_FILENAME} || "";

my $config = {
    compile => {
        inc => ['lib', 't/lib', 'xt/lib'],
        # append inc only if files are in your projects
        # $filename =~ /my_project/ ? ( inc => ['lib', 't/lib', 'xt/lib'] ) : (),
    },
    regexp => {
        # some options
    },
    custom => {
        # some options
    },
};

```

**Comment by oalders** [comment]
@skaji I will put something together to use the config for finding libs.  In the meantime, I've moved `g:ale_perl_syntax_check_executable` to #8

**Comment by oalders** [comment]
I believe the issue with the libs should be resolved via #9

**Pull request closed without merging**
